#!/bin/bash

LAYOUT_DIR="/home/mdiloreto/.config/hypr/layouts"
GENERATED_DIR="$LAYOUT_DIR/generated"
LAYOUT_CONF="/home/mdiloreto/.config/hypr/workspaces_layout.conf"
AUTO_START="# --- AUTOGENERATED LAYOUTS START ---"
AUTO_END="# --- AUTOGENERATED LAYOUTS END ---"

mkdir -p "$GENERATED_DIR"

# Remove previously generated layouts without touching manual scripts
find "$GENERATED_DIR" -maxdepth 1 -type f -name 'ws_*_auto.sh' -delete

declare -A workspace_pids
# Capture all clients grouped by workspace
while IFS=: read -r workspace_id pid; do
    workspace_pids["$workspace_id"]+="$pid "
done < <(hyprctl -j clients | jq -r '.[] | select(.pid != -1) | "\(.workspace.id):\(.pid)"')

# Sort workspace ids numerically for deterministic output
workspace_ids=()
for ws_id in "${!workspace_pids[@]}"; do
    workspace_ids+=("$ws_id")
done
IFS=$'\n' workspace_ids=($(sort -n <<<"${workspace_ids[*]}"))
unset IFS

auto_lines=""

for ws_id in "${workspace_ids[@]}"; do
    ws_script="$GENERATED_DIR/ws_${ws_id}_auto.sh"
    {
        echo "#!/bin/bash"
        has_cmd=0
        for pid in ${workspace_pids[$ws_id]}; do
            cmdline=$(tr '\0' ' ' < "/proc/$pid/cmdline")
            [[ -n "$cmdline" ]] || continue
            echo "$cmdline &"
            has_cmd=1
        done
    } > "$ws_script"

    if [[ $has_cmd -eq 0 ]]; then
        rm -f "$ws_script"
        continue
    fi

    chmod +x "$ws_script"
    auto_lines+="workspace = ${ws_id}, on-created-empty:bash ${ws_script}\\n"
done

# Strip any existing autogenerated block from the config
tmp_conf=$(mktemp)
if [[ -f "$LAYOUT_CONF" ]]; then
    awk -v start="$AUTO_START" -v end="$AUTO_END" '
        $0 == start {in_block=1; next}
        in_block && $0 == end {in_block=0; next}
        !in_block {print}
    ' "$LAYOUT_CONF" > "$tmp_conf"
else
    : > "$tmp_conf"
fi

# Ensure a blank line before the autogenerated block when manual entries exist
if [[ -s "$tmp_conf" ]]; then
    printf '\n' >> "$tmp_conf"
fi

{
    echo "$AUTO_START"
    echo "# (managed by scripts/save_layout.sh)"
    if [[ -n "$auto_lines" ]]; then
        printf "%b" "$auto_lines"
    fi
    echo "$AUTO_END"
} >> "$tmp_conf"

mv "$tmp_conf" "$LAYOUT_CONF"
